import React, { useState } from 'react';

export default function Practice() {
  const [selectedSubject, setSelectedSubject] = useState('dbms');
  const [companyType, setCompanyType] = useState('product_based');

  return (
    <div className="practice-page">
      <div className="ledger-card">
        <h2 className="ledger-card-title">Mock Interview Practice Flow</h2>
        <p className="text-muted" style={{ marginBottom: '1rem', fontSize: '0.9rem' }}>
          Questions are dynamically generated by Self-RAG from ingested textbook chunks.
        </p>

        <div style={{ display: 'flex', gap: '1rem', marginBottom: '1rem' }}>
          <div>
            <label style={{ display: 'block', fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
              Subject:
            </label>
            <select
              value={selectedSubject}
              onChange={(e) => setSelectedSubject(e.target.value)}
              style={{
                background: 'var(--bg-surface-hover)',
                color: 'var(--text-primary)',
                border: '1px solid var(--border-color)',
                padding: '0.4rem 0.8rem',
                borderRadius: 'var(--radius-sm)',
              }}
            >
              <option value="dbms">DBMS</option>
              <option value="dsa">DSA (Coming Soon)</option>
              <option value="os">OS (Coming Soon)</option>
              <option value="cn">CN (Coming Soon)</option>
              <option value="oop">OOP (Coming Soon)</option>
            </select>
          </div>

          <div>
            <label style={{ display: 'block', fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
              Company Type Tag:
            </label>
            <select
              value={companyType}
              onChange={(e) => setCompanyType(e.target.value)}
              style={{
                background: 'var(--bg-surface-hover)',
                color: 'var(--text-primary)',
                border: '1px solid var(--border-color)',
                padding: '0.4rem 0.8rem',
                borderRadius: 'var(--radius-sm)',
              }}
            >
              <option value="product_based">Product Based</option>
              <option value="mass_recruiter_it">Mass Recruiter IT</option>
              <option value="core_engineering">Core Engineering</option>
            </select>
          </div>
        </div>

        <button className="btn btn-primary">Start Practice Session</button>
      </div>
    </div>
  );
}
